### ISSUE TITLE
No data being displayed

### ISSUE THREAD

**Issue by rummanwaqar** [richards-tech/RTIMULib-Teensy#1]
Using MPU9150 with Teensy 3.1 on Arduino 1.0.6 IDE
```
Pose:: roll:, pitch:, yaw:
Pose:: roll:, pitch:, yaw:
Pose:: roll:, pitch:, yaw:
Sample rate: 51, gyro bias valid
```

**Comment by richardbarnett** [comment]
Never seen that before. To get that display at all quite a lot is working. Are you using Teensyduino V1.21? 

Something you could try is adding a line:

    Serial.println(imuData.fusionPose.x());

after line 97 of TeensyIMU.ino. That will do a direct print of the roll value instead of using an RTMath function. y() and z() would be pitch and yaw respectively.
